---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
    name: sputnikvm-public
    description: SputnikVM repository
spec:
    targets:
        - ./core/.catalog-info.yaml
        - ./runtime/.catalog-info.yaml
        - ./gasometer/.catalog-info.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    name: sputnikvm-evm
    title: SputnikVM evm
    description: Main library that re-exports most things
    tags:
        - ethereum
    links: []
    annotations:
        aurora.dev/security-tier: "1"
spec:
    owner: engine-team
    type: library
    lifecycle: production
