apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    name: sputnikvm-runtime
    title: SputnikVM runtime
    description: Runtime defining interface for block, transaction, and storage
    tags:
        - ethereum
    links: []
    annotations:
        aurora.dev/security-tier: "1"
spec:
    owner: engine-team
    type: library
    lifecycle: production
    subcomponentOf: sputnikvm-evm
