[package]
name = "evm-fuzzer"
version = "0.2.0-dev"
authors = ["Vincent Ulitzsch <vincent@srlabs.de>"]
edition = "2021"
description = "Fuzzer for EVM."
license = "Apache-2.0"

[dependencies]
honggfuzz = "0.5"

evm-core.workspace = true

[[bin]]
name = "evm_fuzz"
path = "src/main.rs"
