name: Ethereum tests

on:
  push:
    branches: [ master ]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  ETHTESTS_VERSION: v17.0
  ETHEREUM_SPEC_TESTS_URL: https://github.com/ethereum/execution-spec-tests/releases/download/pectra-devnet-6%40v1.0.0/fixtures_pectra-devnet-6.tar.gz
  ETHEREUM_SPEC_TESTS2_URL: https://github.com/ethereum/execution-spec-tests/releases/download/v4.4.0/fixtures_stable.tar.gz
  ETHEREUM_SPEC_TESTS_STATIC_URL: https://github.com/ethereum/execution-spec-tests/releases/download/v4.4.0/fixtures_static.tar.gz

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Run tests
        run: cargo test --all --verbose

  unit-tests-32-bit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Run tests 32 bit
        uses: vxcontrol/run-on-arch-action@0.9.0
        id: tests
        with:
          arch: i386
          distro: bullseye
          githubToken: ${{ github.token }}
          run: |
            apt-get update && apt-get install -y curl clang llvm
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            export PATH="$PATH:$HOME/.cargo/bin"
            cargo test --all --verbose

  ethereum-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Checkout ethereum/tests
        uses: actions/checkout@v4
        with:
          repository: ethereum/tests
          path: ethtests
          ref: ${{ env.ETHTESTS_VERSION }}
          submodules: recursive
          fetch-depth: 1

      - name: Download Ethereum spec tests fixtures
        run: |
          curl -L ${{ env.ETHEREUM_SPEC_TESTS_URL }} -o ethereum-spec-tests.tar.gz
          mkdir ethereum-spec-tests
          tar -xzf ethereum-spec-tests.tar.gz -C ethereum-spec-tests

      - name: Download Ethereum spec tests 2 fixtures
        run: |
          curl -L ${{ env.ETHEREUM_SPEC_TESTS2_URL }} -o ethereum-spec-tests2.tar.gz
          mkdir ethereum-spec-tests2
          tar -xzf ethereum-spec-tests2.tar.gz -C ethereum-spec-tests2

      - name: Download Ethereum spec tests fixtures static
        run: |
          curl -L ${{ env.ETHEREUM_SPEC_TESTS_STATIC_URL }} -o ethereum-spec-tests-static.tar.gz
          mkdir ethereum-spec-tests-static
          tar -xzf ethereum-spec-tests-static.tar.gz -C ethereum-spec-tests-static

      - name: Run Ethereum state tests
        run: |
          cargo run -r -p evm-jsontests -F enable-slow-tests -- state -f \
          ethtests/GeneralStateTests/ \
          ethereum-spec-tests-static/fixtures/state_tests/ \
          ethtests/LegacyTests/Cancun/GeneralStateTests/ \
          ethereum-spec-tests/fixtures/state_tests/ \
          ethereum-spec-tests2/fixtures/state_tests/

      - name: Run Ethereum vm tests
        run: |
          cargo run -r -p evm-jsontests -F enable-slow-tests -- vm -f \
            ethtests/LegacyTests/Constantinople/VMTests/vmArithmeticTest \
            ethtests/LegacyTests/Constantinople/VMTests/vmBitwiseLogicOperation \
            ethtests/LegacyTests/Constantinople/VMTests/vmBlockInfoTest \
            ethtests/LegacyTests/Constantinople/VMTests/vmEnvironmentalInfo \
            ethtests/LegacyTests/Constantinople/VMTests/vmIOandFlowOperations \
            ethtests/LegacyTests/Constantinople/VMTests/vmLogTest \
            ethtests/LegacyTests/Constantinople/VMTests/vmPerformance \
            ethtests/LegacyTests/Constantinople/VMTests/vmPushDupSwapTest \
            ethtests/LegacyTests/Constantinople/VMTests/vmRandomTest \
            ethtests/LegacyTests/Constantinople/VMTests/vmSha3Test \
            ethtests/LegacyTests/Constantinople/VMTests/vmSystemOperations \
            ethtests/LegacyTests/Constantinople/VMTests/vmTests

  ethereum-tests-32-bit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Checkout ethereum/tests
        uses: actions/checkout@v4
        with:
          repository: ethereum/tests
          path: ethtests
          ref: ${{ env.ETHTESTS_VERSION }}
          submodules: recursive
          fetch-depth: 1

      - name: Run Ethereum state tests 32 bit
        uses: vxcontrol/run-on-arch-action@0.9.0
        id: tests
        with:
          arch: i386
          distro: bullseye
          githubToken: ${{ github.token }}
          run: |
            apt-get update && apt-get install -y curl wget clang llvm
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            export PATH="$PATH:$HOME/.cargo/bin"

            curl -L ${{ env.ETHEREUM_SPEC_TESTS_URL }} -o ethereum-spec-tests.tar.gz
            mkdir ethereum-spec-tests
            tar -xzf ethereum-spec-tests.tar.gz -C ethereum-spec-tests

            curl -L ${{ env.ETHEREUM_SPEC_TESTS2_URL }} -o ethereum-spec-tests2.tar.gz
            mkdir ethereum-spec-tests2
            tar -xzf ethereum-spec-tests2.tar.gz -C ethereum-spec-tests2

            curl -L ${{ env.ETHEREUM_SPEC_TESTS_STATIC_URL }} -o ethereum-spec-tests-static.tar.gz
            mkdir ethereum-spec-tests-static
            tar -xzf ethereum-spec-tests-static.tar.gz -C ethereum-spec-tests-static

            cargo run -r -p evm-jsontests -F enable-slow-tests -- state -f \
              ethtests/GeneralStateTests/ \
              ethereum-spec-tests-static/fixtures/state_tests/ \
              ethtests/LegacyTests/Cancun/GeneralStateTests/ \
              ethereum-spec-tests/fixtures/state_tests/ \
              ethereum-spec-tests2/fixtures/state_tests/

            cargo run -r -p evm-jsontests -F enable-slow-tests -- vm -f \
              ethtests/LegacyTests/Constantinople/VMTests/vmArithmeticTest \
              ethtests/LegacyTests/Constantinople/VMTests/vmBitwiseLogicOperation \
              ethtests/LegacyTests/Constantinople/VMTests/vmBlockInfoTest \
              ethtests/LegacyTests/Constantinople/VMTests/vmEnvironmentalInfo \
              ethtests/LegacyTests/Constantinople/VMTests/vmIOandFlowOperations \
              ethtests/LegacyTests/Constantinople/VMTests/vmLogTest \
              ethtests/LegacyTests/Constantinople/VMTests/vmPerformance \
              ethtests/LegacyTests/Constantinople/VMTests/vmPushDupSwapTest \
              ethtests/LegacyTests/Constantinople/VMTests/vmRandomTest \
              ethtests/LegacyTests/Constantinople/VMTests/vmSha3Test \
              ethtests/LegacyTests/Constantinople/VMTests/vmSystemOperations \
              ethtests/LegacyTests/Constantinople/VMTests/vmTests
