name: Rust

on:
  push:
    branches: [ master ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rustfmt
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --workspace --all-targets -- -D clippy::all -D clippy::nursery
      - name: Clippy no_std
        run: cargo clippy --no-default-features -- -D clippy::all -D clippy::nursery
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Build NoStd
        run: cargo build --no-default-features
      - name: Build for feature (tracing)
        run: cargo build --features tracing
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run tests
        run: cargo test --all --verbose
  ethereum-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Checkout ethereum/tests
        uses: actions/checkout@v4
        with:
          repository: ethereum/tests
          path: ethtests
          ref: v13.2
          submodules: recursive

      - name: Run Ethereum state tests
        run: |
          cargo run -r -p evm-jsontests -F enable-slow-tests -- \
          	state -f \
          	ethtests/GeneralStateTests/

      - name: Run Ethereum vm tests
        run: |
          cargo run -r -p evm-jsontests -F enable-slow-tests -- \
          	vm -f \
            ethtests/LegacyTests/Constantinople/VMTests/vmArithmeticTest \
            ethtests/LegacyTests/Constantinople/VMTests/vmBitwiseLogicOperation \
            ethtests/LegacyTests/Constantinople/VMTests/vmBlockInfoTest \
            ethtests/LegacyTests/Constantinople/VMTests/vmEnvironmentalInfo \
            ethtests/LegacyTests/Constantinople/VMTests/vmIOandFlowOperations \
            ethtests/LegacyTests/Constantinople/VMTests/vmLogTest \
            ethtests/LegacyTests/Constantinople/VMTests/vmPerformance \
            ethtests/LegacyTests/Constantinople/VMTests/vmPushDupSwapTest \
            ethtests/LegacyTests/Constantinople/VMTests/vmRandomTest \
            ethtests/LegacyTests/Constantinople/VMTests/vmSha3Test \
            ethtests/LegacyTests/Constantinople/VMTests/vmSystemOperations \
            ethtests/LegacyTests/Constantinople/VMTests/vmTests
