---
name: "Security Analysis"

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  contract_analysis:
    name: "Shared"
    uses: aurora-is-near/.github/.github/workflows/security_analysis.yml@master
    secrets: inherit
